<?php

use App\Models\DeviceModel;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        $deviceModels = [
            [
                'name' => 'v2',
                'label' => 'TRMNL X',
                'description' => 'TRMNL X',
                'width' => 1872,
                'height' => 1404,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.8,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'trmnl',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'og_png',
                'label' => 'TRMNL OG (1-bit)',
                'description' => 'TRMNL OG (1-bit)',
                'width' => 800,
                'height' => 480,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'trmnl',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_2024',
                'label' => 'Amazon Kindle 2024',
                'description' => 'Amazon Kindle 2024',
                'width' => 1400,
                'height' => 840,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.75,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 75,
                'offset_y' => 25,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_paperwhite_6th_gen',
                'label' => 'Amazon Kindle PW 6th Gen',
                'description' => 'Amazon Kindle PW 6th Gen',
                'width' => 1024,
                'height' => 768,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.28,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_paperwhite_7th_gen',
                'label' => 'Amazon Kindle PW 7th Gen',
                'description' => 'Amazon Kindle PW 7th Gen',
                'width' => 1448,
                'height' => 1072,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.6,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'inkplate_10',
                'label' => 'Inkplate 10',
                'description' => 'Inkplate 10',
                'width' => 1200,
                'height' => 825,
                'colors' => 8,
                'bit_depth' => 3,
                'scale_factor' => 1.5,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_7',
                'label' => 'Amazon Kindle 7',
                'description' => 'Amazon Kindle 7',
                'width' => 800,
                'height' => 600,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.0,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'inky_impression_7_3',
                'label' => 'Inky Impression 7.3',
                'description' => 'Inky Impression 7.3',
                'width' => 800,
                'height' => 480,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_libra_2',
                'label' => 'Kobo Libra 2',
                'description' => 'Kobo Libra 2',
                'width' => 1680,
                'height' => 1264,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 2.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_oasis_2',
                'label' => 'Amazon Kindle Oasis 2',
                'description' => 'Amazon Kindle Oasis 2',
                'width' => 1680,
                'height' => 1264,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 2.1,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'og_plus',
                'label' => 'TRMNL OG (2-bit)',
                'description' => 'TRMNL OG (2-bit)',
                'width' => 800,
                'height' => 480,
                'colors' => 4,
                'bit_depth' => 2,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'trmnl',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_aura_one',
                'label' => 'Kobo Aura One',
                'description' => 'Kobo Aura One',
                'width' => 1872,
                'height' => 1404,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.8,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_aura_hd',
                'label' => 'Kobo Aura HD',
                'description' => 'Kobo Aura HD',
                'width' => 1440,
                'height' => 1080,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.8,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'inky_impression_13_3',
                'label' => 'Inky Impression 13.3',
                'description' => 'Inky Impression 13.3',
                'width' => 1600,
                'height' => 1200,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 2.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'm5_paper_s3',
                'label' => 'M5PaperS3',
                'description' => 'M5PaperS3',
                'width' => 960,
                'height' => 540,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_scribe',
                'label' => 'Amazon Kindle Scribe',
                'description' => 'Amazon Kindle Scribe',
                'width' => 2480,
                'height' => 1860,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 2.5,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'seeed_e1001',
                'label' => 'Seeed E1001 Monochrome',
                'description' => 'Seeed E1001 Monochrome',
                'width' => 800,
                'height' => 480,
                'colors' => 4,
                'bit_depth' => 2,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'seeed_e1002',
                'label' => 'Seeed E1002 (2-bit)',
                'description' => 'Seeed E1002 (2-bit)',
                'width' => 800,
                'height' => 480,
                'colors' => 4,
                'bit_depth' => 2,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'waveshare_4_26',
                'label' => 'Waveshare 4.26" (2-bit)',
                'description' => 'Waveshare 4.26" (2-bit)',
                'width' => 800,
                'height' => 480,
                'colors' => 4,
                'bit_depth' => 2,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'waveshare_7_5_bw',
                'label' => 'Waveshare 7.5" B/W',
                'description' => 'Waveshare 7.5" B/W',
                'width' => 800,
                'height' => 480,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'tidbyt',
                'label' => 'Tidbyt',
                'description' => 'Tidbyt',
                'width' => 64,
                'height' => 32,
                'colors' => 16777216,
                'bit_depth' => 24,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/webp',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'tidbyt',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'generic_16_9',
                'label' => 'Generic 16:9 Display',
                'description' => 'Generic 16:9 Display',
                'width' => 1920,
                'height' => 1080,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 2.4,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'palma',
                'label' => 'Onyx BOOX Palma',
                'description' => 'Onyx BOOX Palma',
                'width' => 1648,
                'height' => 824,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 2.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'onyx_boox_go_7',
                'label' => 'Onyx BOOX Go 7',
                'description' => 'Onyx BOOX Go 7',
                'width' => 1880,
                'height' => 1264,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.8008,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_glo',
                'label' => 'Kobo Glo',
                'description' => 'Kobo Glo',
                'width' => 1024,
                'height' => 768,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.2995,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'waveshare_7_5_bwr',
                'label' => 'Waveshare 7.5" B/W/R',
                'description' => 'Waveshare 7.5" B/W/R',
                'width' => 800,
                'height' => 480,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'waveshare_7_5_bwry',
                'label' => 'Waveshare 7.5" B/W/R/Y',
                'description' => 'Waveshare 7.5" B/W/R/Y',
                'width' => 800,
                'height' => 480,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'onxy_boox_nova_air_c',
                'label' => 'Onyx BOOX Nova Air C',
                'description' => 'Onyx BOOX Nova Air C',
                'width' => 1872,
                'height' => 1404,
                'colors' => 4096,
                'bit_depth' => 12,
                'scale_factor' => 1.8,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'xteink_x4',
                'label' => 'Xteink X4',
                'description' => 'Xteink X4',
                'width' => 800,
                'height' => 480,
                'colors' => 4,
                'bit_depth' => 2,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nook_simple_touch',
                'label' => 'Nook Simple Touch',
                'description' => 'Nook Simple Touch',
                'width' => 800,
                'height' => 600,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.0,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_sage',
                'label' => 'Kobo Sage',
                'description' => 'Kobo Sage',
                'width' => 1920,
                'height' => 1440,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.4004,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'og_bwry',
                'label' => 'TRMNL OG (B/W/R/Y)',
                'description' => 'TRMNL OG (B/W/R/Y)',
                'width' => 800,
                'height' => 480,
                'colors' => 2,
                'bit_depth' => 1,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'trmnl',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_voyage',
                'label' => 'Amazon Kindle Voyage',
                'description' => 'Amazon Kindle Voyage',
                'width' => 1448,
                'height' => 1072,
                'colors' => 256,
                'bit_depth' => 8,
                'scale_factor' => 1.4008,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'inkplate_5_2',
                'label' => 'Inkplate 5.2',
                'description' => 'Inkplate 5.2',
                'width' => 1280,
                'height' => 720,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.1996,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'raspberry_pi_touch_2',
                'label' => 'Raspberry Pi Touch 2',
                'description' => 'Raspberry Pi Touch 2',
                'width' => 1280,
                'height' => 720,
                'colors' => 16777216,
                'bit_depth' => 24,
                'scale_factor' => 1.1996,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ed133ut2',
                'label' => 'ED133UT2 Active Matrix',
                'description' => 'ED133UT2 Active Matrix',
                'width' => 1600,
                'height' => 1200,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.5385,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'avalue_epd_42s',
                'label' => 'Avalue EPD-42S 42" Display Board',
                'description' => 'Avalue EPD-42S 42" Display Board',
                'width' => 2880,
                'height' => 2160,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 2.7692,
                'rotation' => 0,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_touch',
                'label' => 'Kobo Touch',
                'description' => 'Kobo Touch',
                'width' => 800,
                'height' => 600,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 1.0,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kobo_forma',
                'label' => 'Kobo Forma',
                'description' => 'Kobo Forma',
                'width' => 1920,
                'height' => 1440,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 2.4,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'openframe',
                'label' => 'OpenPeak OpenFrame',
                'description' => 'OpenPeak OpenFrame',
                'width' => 800,
                'height' => 480,
                'colors' => 16777216,
                'bit_depth' => 24,
                'scale_factor' => 1.0,
                'rotation' => 0,
                'mime_type' => 'image/webp',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'byod',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazon_kindle_paperwhite_signature_11th_gen',
                'label' => 'Amazon Kindle PW Signature 11th Gen',
                'description' => 'Amazon Kindle PW Signature 11th Gen',
                'width' => 1648,
                'height' => 1236,
                'colors' => 16,
                'bit_depth' => 4,
                'scale_factor' => 2.06,
                'rotation' => 90,
                'mime_type' => 'image/png',
                'offset_x' => 0,
                'offset_y' => 0,
                'kind' => 'kindle',
                'source' => 'api',
                'published_at' => '2024-01-01 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DeviceModel::query()->upsert(
            $deviceModels,
            ['name'],
            ['label', 'description', 'width', 'height', 'colors', 'bit_depth', 'scale_factor',
             'rotation', 'mime_type', 'offset_x', 'offset_y', 'kind', 'published_at', 'source',
             'created_at', 'updated_at']
        );
    }

    public function down(): void
    {
        $names = [
            'v2',
            'og_png',
            'amazon_kindle_2024',
            'amazon_kindle_paperwhite_6th_gen',
            'amazon_kindle_paperwhite_7th_gen',
            'inkplate_10',
            'amazon_kindle_7',
            'inky_impression_7_3',
            'kobo_libra_2',
            'amazon_kindle_oasis_2',
            'og_plus',
            'kobo_aura_one',
            'kobo_aura_hd',
            'inky_impression_13_3',
            'm5_paper_s3',
            'amazon_kindle_scribe',
            'seeed_e1001',
            'seeed_e1002',
            'waveshare_4_26',
            'waveshare_7_5_bw',
            'tidbyt',
            'generic_16_9',
            'palma',
            'onyx_boox_go_7',
            'kobo_glo',
            'waveshare_7_5_bwr',
            'waveshare_7_5_bwry',
            'onxy_boox_nova_air_c',
            'xteink_x4',
            'nook_simple_touch',
            'kobo_sage',
            'og_bwry',
            'amazon_kindle_voyage',
            'inkplate_5_2',
            'raspberry_pi_touch_2',
            'ed133ut2',
            'avalue_epd_42s',
            'kobo_touch',
            'kobo_forma',
            'openframe',
            'amazon_kindle_paperwhite_signature_11th_gen'
        ];

        DeviceModel::query()->whereIn('name', $names)->delete();
    }
};
